# A list of devices you want to take the screenshots from
devices([
  "iPhone 6s Plus"
])
 
# A list of supported languages
languages([
  'en-US'
])
 
# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"
 
# Clears previous screenshots
clear_previous_screenshots true
